version: "3"
services:
  flask:
    image: "progdrum/nhl-viz-app:v0.1"
    container_name: "gunicorn-flask"
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
  bokeh:
    image: "progdrum/nhl-bokeh-apps:v0.1"
    container_name: "bokeh-viz"
    build: ./bokeh_apps
    ports:
      - "5006:5006"
    depends_on:
      - db
    db:
      image: "mongo:latest"
      container_name: "mongo-db"
